<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('products')->insert([
            // Drinks
            ['name' => 'Americano', 'image' => 'americano.png', 'description' => 'A smooth blend of water and espresso for a balanced coffee experience. Perfect for those who enjoy a lighter coffee with bold flavours.', 'price' => 3.99, 'size' => 'small', 'stock' => 100, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Americano', 'image' => 'americano.png', 'description' => 'A smooth blend of water and espresso for a balanced coffee experience. Perfect for those who enjoy a lighter coffee with bold flavours.', 'price' => 4.99, 'size' => 'medium', 'stock' => 80, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Americano', 'image' => 'americano.png', 'description' => 'A smooth blend of water and espresso for a balanced coffee experience. Perfect for those who enjoy a lighter coffee with bold flavours.', 'price' => 5.99, 'size' => 'large', 'stock' => 60, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Cappuccino', 'image' => 'cappuccino.png', 'description' => 'A classic Italian coffee with a perfect mix of rich espresso, creamy steamed milk, and a frothy foam topping. Ideal for starting your day or as a treat.', 'price' => 4.49, 'size' => 'small', 'stock' => 120, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cappuccino', 'image' => 'cappuccino.png', 'description' => 'A classic Italian coffee with a perfect mix of rich espresso, creamy steamed milk, and a frothy foam topping. Ideal for starting your day or as a treat.', 'price' => 5.49, 'size' => 'medium', 'stock' => 100, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cappuccino', 'image' => 'cappuccino.png', 'description' => 'A classic Italian coffee with a perfect mix of rich espresso, creamy steamed milk, and a frothy foam topping. Ideal for starting your day or as a treat.', 'price' => 6.49, 'size' => 'large', 'stock' => 80, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Espresso', 'image' => 'espresso.png', 'description' => 'A strong and rich coffee shot with an intense aroma and a velvety crema on top.', 'price' => 3.49, 'size' => 'small', 'stock' => 150, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Espresso', 'image' => 'espresso.png', 'description' => 'A strong and rich coffee shot with an intense aroma and a velvety crema on top.', 'price' => 4.49, 'size' => 'medium', 'stock' => 120, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Espresso', 'image' => 'espresso.png', 'description' => 'A strong and rich coffee shot with an intense aroma and a velvety crema on top.', 'price' => 4.99, 'size' => 'large', 'stock' => 90, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Flat White', 'image' => 'flatwhite.png', 'description' => 'A velvety coffee made with a smooth blend of espresso and steamed milk. Known for its creamy texture and balanced flavour, its a favourite among coffee aficionados.', 'price' => 5.49, 'size' => 'small', 'stock' => 80, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Flat White', 'image' => 'flatwhite.png', 'description' => 'A velvety coffee made with a smooth blend of espresso and steamed milk. Known for its creamy texture and balanced flavour, its a favourite among coffee aficionados.', 'price' => 6.49, 'size' => 'medium', 'stock' => 70, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Flat White', 'image' => 'flatwhite.png', 'description' => 'A velvety coffee made with a smooth blend of espresso and steamed milk. Known for its creamy texture and balanced flavour, its a favourite among coffee aficionados.', 'price' => 6.99, 'size' => 'large', 'stock' => 60, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Hot Chocolate', 'image' => 'hotchocolate.png', 'description' => 'A comforting and creamy chocolate drink in a pod. It offers a rich, indulgent taste perfect for warming up on cold days or as a sweet treat.', 'price' => 4.49, 'size' => 'small', 'stock' => 110, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hot Chocolate', 'image' => 'hotchocolate.png', 'description' => 'A comforting and creamy chocolate drink in a pod. It offers a rich, indulgent taste perfect for warming up on cold days or as a sweet treat.', 'price' => 5.49, 'size' => 'medium', 'stock' => 90, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hot Chocolate', 'image' => 'hotchocolate.png', 'description' => 'A comforting and creamy chocolate drink in a pod. It offers a rich, indulgent taste perfect for warming up on cold days or as a sweet treat.', 'price' => 6.49, 'size' => 'large', 'stock' => 70, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Latte', 'image' => 'latte.png', 'description' => 'A creamy and smooth coffee with a perfect balance of espresso and milk. An all-time favourite great for those who enjoy a mellow and satisfying coffee experience.', 'price' => 5.49, 'size' => 'small', 'stock' => 90, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Latte', 'image' => 'latte.png', 'description' => 'A creamy and smooth coffee with a perfect balance of espresso and milk. An all-time favourite great for those who enjoy a mellow and satisfying coffee experience.', 'price' => 6.49, 'size' => 'medium', 'stock' => 70, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Latte', 'image' => 'latte.png', 'description' => 'A creamy and smooth coffee with a perfect balance of espresso and milk. An all-time favourite great for those who enjoy a mellow and satisfying coffee experience.', 'price' => 7.49, 'size' => 'large', 'stock' => 50, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Macchiato', 'image' => 'macchiato.png', 'description' => 'A bold espresso with a delicate layer of foamed milk. This classic drink is ideal for those who prefer a stronger coffee flavour with a hint of creaminess.', 'price' => 5.49, 'size' => 'small', 'stock' => 70, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Macchiato', 'image' => 'macchiato.png', 'description' => 'A bold espresso with a delicate layer of foamed milk. This classic drink is ideal for those who prefer a stronger coffee flavour with a hint of creaminess.', 'price' => 6.49, 'size' => 'medium', 'stock' => 50, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Macchiato', 'image' => 'macchiato.png', 'description' => 'A bold espresso with a delicate layer of foamed milk. This classic drink is ideal for those who prefer a stronger coffee flavour with a hint of creaminess.', 'price' => 7.49, 'size' => 'large', 'stock' => 30, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Mocha', 'image' => 'mocha.png', 'description' => 'A delightful fusion of rich coffee, smooth chocolate, and creamy milk. This indulgent beverage is perfect for chocolate lovers seeking a luxurious coffee experience.', 'price' => 5.49, 'size' => 'small', 'stock' => 60, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mocha', 'image' => 'mocha.png', 'description' => 'A delightful fusion of rich coffee, smooth chocolate, and creamy milk. This indulgent beverage is perfect for chocolate lovers seeking a luxurious coffee experience.', 'price' => 6.49, 'size' => 'medium', 'stock' => 40, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mocha', 'image' => 'mocha.png', 'description' => 'A delightful fusion of rich coffee, smooth chocolate, and creamy milk. This indulgent beverage is perfect for chocolate lovers seeking a luxurious coffee experience.', 'price' => 7.49, 'size' => 'large', 'stock' => 20, 'category_id' => 1, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Americano Pods', 'image' => 'pod_americano.png', 'description' => 'A rich and bold Americano coffee pod that delivers a smooth and balanced flavour. Enjoy the classic coffee shop experience in the comfort of your home.', 'price' => 5.99, 'size' => 'one-size', 'stock' => 100, 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cappuccino Pods', 'image' => 'pod_cappuccino.png', 'description' => 'Creamy cappuccino in a convenient pod. Indulge in a harmonious blend of espresso, steamed milk, and frothy foam for a café-style treat.', 'price' => 6.49, 'size' => 'one-size', 'stock' => 120, 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Espresso Pods', 'image' => 'pod_espresso.png', 'description' => 'Classic espresso pod for a quick shot of intense flavour. Perfect for those who love a bold and aromatic coffee with a velvety crema.', 'price' => 4.99, 'size' => 'one-size', 'stock' => 150, 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Flat White Pods', 'image' => 'pod_flatwhite.png', 'description' => 'Smooth and velvety flat white pod crafted with a balanced mix of espresso and steamed milk. A luxurious coffee experience for any time of day.', 'price' => 6.99, 'size' => 'one-size', 'stock' => 80, 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hot Chocolate Pods', 'image' => 'pod_hotchocolate.png', 'description' => 'Delicious hot chocolate in a pod, offering a rich and creamy cocoa flavour. Ideal for cosy evenings or a delightful treat for kids and adults alike.', 'price' => 5.49, 'size' => 'one-size', 'stock' => 110, 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Latte Pods', 'image' => 'pod_latte.png', 'description' => 'Creamy latte pod for coffee lovers. With its smooth texture and mellow coffee flavour, it\'s the perfect way to relax and savour a moment of indulgence.', 'price' => 6.49, 'size' => 'one-size', 'stock' => 90, 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Macchiato Pods', 'image' => 'pod_macchiato.png', 'description' => 'Intense and flavourful macchiato pod that combines bold espresso with a hint of creamy milk. A sophisticated choice for coffee enthusiasts.', 'price' => 6.99, 'size' => 'one-size', 'stock' => 70, 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Mocha Pods', 'image' => 'pod_mocha.png', 'description' => 'Chocolatey mocha pod for indulgence. A decadent blend of rich coffee, smooth chocolate, and creamy milk, perfect for a luxurious coffee moment.', 'price' => 6.99, 'size' => 'one-size', 'stock' => 60, 'category_id' => 2, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Brazilian Beans', 'image' => 'bag_brazilian.png', 'description' => 'Rich and smooth Brazilian coffee beans with a nutty aroma and hints of chocolate. Perfect for creating a well-rounded, medium-bodied cup.', 'price' => 12.99, 'size' => 'one-size', 'stock' => 50, 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Colombian Beans', 'image' => 'bag_colombian.png', 'description' => 'Bright and fruity Colombian coffee beans featuring citrusy notes and a delightful sweetness. Ideal for those who enjoy a lively and aromatic brew.', 'price' => 13.49, 'size' => 'one-size', 'stock' => 60, 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ethiopian Beans', 'image' => 'bag_ethiopian.png', 'description' => 'Floral and aromatic Ethiopian coffee beans with delicate notes of jasmine and a tea-like quality. A favourite for lovers of unique, complex flavours.', 'price' => 14.99, 'size' => 'one-size', 'stock' => 40, 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Jamaican Beans', 'image' => 'bag_jamaican.png', 'description' => 'Bold and flavourful Jamaican coffee beans with a smooth, rich taste and hints of tropical fruits. Known for their exceptional quality and depth.', 'price' => 15.99, 'size' => 'one-size', 'stock' => 30, 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kenyan Beans', 'image' => 'bag_kenyan.png', 'description' => 'Crisp and vibrant Kenyan coffee beans with bright acidity and flavours of blackcurrant and citrus. Perfect for those seeking a bold and invigorating cup.', 'price' => 13.99, 'size' => 'one-size', 'stock' => 70, 'category_id' => 3, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Chocolate Twist', 'image' => 'chocolate_twist.png', 'description' => 'A delightful twisted pastry filled with decadent, creamy chocolate and topped with a sprinkle of crunchy nuts. Perfect for a quick indulgent treat.', 'price' => 3.99, 'size' => 'one-size', 'stock' => 40, 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cinnamon Roll', 'image' => 'cinnamon_roll.png', 'description' => 'Soft and warm cinnamon roll swirled with a rich cinnamon filling and topped with a sweet, luscious glaze. A classic comfort food for any time of day.', 'price' => 3.79, 'size' => 'one-size', 'stock' => 30, 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Croissant', 'image' => 'croissant.png', 'description' => 'A flaky and buttery croissant with a golden, crisp exterior and soft, airy layers inside. Perfect for pairing with coffee or as a standalone treat', 'price.' => 3.49, 'size' => 'one-size', 'stock' => 50, 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pain Au Chocolat', 'image' => 'pain_au_chocolat.png', 'description' => 'A delicious, buttery croissant filled with rich, velvety dark chocolate. A classic French pastry that\'s perfect for breakfast or dessert.', 'price' => 4.49, 'size' => 'one-size', 'stock' => 60, 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pie', 'image' => 'pie.png', 'description' => 'A freshly baked pie with a perfectly flaky crust and a rich, flavourful fruit filling. Ideal for sharing at family gatherings or enjoying solo.', 'price' => 5.99, 'size' => 'one-size', 'stock' => 70, 'category_id' => 4, 'created_at' => now(), 'updated_at' => now()],

            ['name' => 'Blueberry Muffin', 'image' => 'blueberry_muffin.png', 'description' => 'Warm and soft muffin bursting with fresh, juicy blueberries and topped with a golden, crumbly streusel. Perfect for breakfast or a delightful snack.', 'price' => 3.99, 'size' => 'one-size', 'stock' => 70, 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chocolate Brownie', 'image' => 'brownie.png', 'description' => 'Rich and indulgent chocolate brownie with a fudgy texture, loaded with intense cocoa flavour and a perfect balance of sweetness. Ideal for satisfying cravings.', 'price' => 4.99, 'size' => 'one-size', 'stock' => 50, 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chocolate Chip Cookie', 'image' => 'cookie.png', 'description' => 'Soft and chewy chocolate chip cookie with gooey chocolate chunks and a perfect balance of sweetness. A comforting treat for any occasion.', 'price' => 2.99, 'size' => 'one-size', 'stock' => 40, 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Chocolate Muffin', 'image' => 'chocolate_muffin.png', 'description' => 'A warm and soft muffin filled with rich, melted chocolate chunks, offering a decadent and indulgent treat Perfect for breakfast or as a delightful snack.', 'price' => 3.99, 'size' => 'one-size', 'stock' => 70, 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pink Iced Doughnut', 'image' => 'iced_doughnut.png', 'description' => 'A soft and airy doughnut topped with a smooth, vibrant pink icing, creating a sweet and colourful treat. The rich, sugary glaze perfectly complements the light, fluffy texture.', 'price' => 3.49, 'size' => 'one-size', 'stock' => 30, 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sugar Ring Doughnut', 'image' => 'sugar_doughnut.png', 'description' => 'A fluffy and light doughnut coated in a fine layer of sweet sugar, offering a simple yet irresistible treat perfect for any time of day.', 'price' => 3.49, 'size' => 'one-size', 'stock' => 30, 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vanilla Cake', 'image' => 'cake.png', 'description' => 'Delicious and moist vanilla cake layered with creamy, velvety frosting. A timeless dessert, perfect for celebrations or a sweet indulgence.', 'price' => 5.49, 'size' => 'one-size', 'stock' => 60, 'category_id' => 5, 'created_at' => now(), 'updated_at' => now()],

        ]);
    }
}
